version: "3.7"

services:
  quote-api:
    image: get-quote
    container_name: get-quote
    build:
      context: .
    ports:
      - 5000:5000
      - 80:80
    environment:
      - FLASK_DEBUG=1
    entrypoint: [ "python3", "-m", "flask", "run", "--host", "0.0.0.0" ]

